[package]
name = "engine"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 2

[dependencies]
ndarray = "0.15.3"
serde = {version="1.0.126", features=["derive"]}
serde_json = "1.0.64"
ruscii = "0.3.2"
